# use / to create a website server locally
baseurl = "https://legends2k.github.io/"
languageCode = "en-uk"
title = "Bits of Insight"
theme = "ghostwriter"
copyright = "Sundaram Ramaswamy"
googleAnalytics = ""
paginate =  7
enableGitInfo = true

[Author]
    name = "Sundaram Ramaswamy"
    profile = "https://legends2k.github.io/about/"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Bits of Insight"
    description = "Building intuition by substantiating"
    email = "legends2k@yahoo.com"
    github = "https://github.com/legends2k"
    linkedin = "https://in.linkedin.com/pub/sundaram-ramaswamy/24/b20/1a0"
    bitbucket = "https://bitbucket.org/rmsundaram"
    stackoverflow = "https://stackoverflow.com/users/183120/legends2k"
    flickr = "https://flickr.com/photos/legends2k"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    readingTime = false
    readingTimeText = ""

[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 1

[[menu.main]]
    name = "Notes"
    url = "/note/"
    weight = 2

[[menu.main]]
    name = "All Posts"
    url = '/archive/'
    weight = 3

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[markup]
    footnoteReturnLinkContents = "↩"

[markup.highlight]
    style = "dracula"
    tabWidth = 2

[markup.tableOfContents]
    startLevel = 1
    endLevel = 2
    ordered = true

# “date” usually means (article’s file) creation date i.e. when the idea was
# first convinced, “lastmod” almost always comes from Git, set “pushlishDate”
# when publishing.  Being explicit is usually better; fallbacks below:
[frontmatter]
    date = ["date", "publishDate", "lastmod"]
    publishDate = ["publishDate", "date"]
    lastmod = [":git", "lastmod", "date", "publishDate"]
